######################################################################
# Automatically generated by qmake (3.0) Tue Jan 24 17:34:07 2017
######################################################################
CONFIG += c++11
TEMPLATE = app
TARGET = app
INCLUDEPATH += . catch

# Input
HEADERS += path.h 
SOURCES += main.cpp module.cpp path.cpp 
